version: '3.8'

services:
  backend:
    # Vincula el servicio directamente con tu imagen seleccionada
    image: krono_back:latest
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - JAVA_OPTS=
    # Permite al contenedor ver el localhost de tu máquina física Windows
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - krono_net

  frontend:
    # Vincula el servicio directamente con tu imagen seleccionada
    image: krono_front:latest
    build:
      context: ./Malla_Turnos
    ports:
      - "4200:4200"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - krono_net

networks:
  krono_net:
    driver: bridge