# ============================================================
# BASE DE DATOS POSTGRESQL
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/Malla?stringtype=unspecified
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456

# ============================================================
# JPA / HIBERNATE
# ============================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# DESACTIVAR H2
# ============================================================
spring.h2.console.enabled=false

# ============================================================
# PUERTO DEL SERVIDOR
# ============================================================
server.port=8081